### ISSUE TITLE
Internal Hostnames

### ISSUE THREAD

**Issue by binary1985** [lair-framework/drone-burp#10]
Seems like internal hostnames are causing the drone to fail. The host names did exist in the LAIR instance. 

./drone-burp_darwin_amd64 -k rZEJi4XPxMMrK9n9x ~/Desktop/internal-findings.xml 
2016/12/14 20:16:21 Could not lookup <redacted internal hostname>
<repeats for each finding and each host>

Using sed to replace the hostnames with the IP's fixed it, but a better solution should be created.

**Comment by tomsteele** [comment]
@jamesbcook any thoughts on this one?
