### ISSUE TITLE
Windows issue?

### ISSUE THREAD

**Issue by overflowwebdesigns** [lair-framework/drone-burp#3]
Should this drone work on a Windows system?  I have setup everything as I think I should and still get 2016/02/23 14:17:03 Fatal: Missing username and/or password.

I did 

set LAIR_API_SERVER='https://admin@localhost:password@my_ip:1013' (I also tried port 11015.

Assuming Windows is just not supported?

**Comment by jamesbcook** [comment]
Yes the drone works on windows.

Try to use the port 11013

**Comment by overflowwebdesigns** [comment]
I do have it set to 11013 the 10013 up top is a typo my bad.

**Comment by jamesbcook** [comment]
Remove the single quotes, so it should look like:

set LAIR_API_SERVER=https://admin@localhost:password@my_ip:11013

**Comment by jamesbcook** [comment]
are you still having issues?

**Comment by overflowwebdesigns** [comment]
Sorry I have been away a few days. Your suggestion solved this issue.  Thank you!
